import { Agent, Alert, CostData, Session, SessionDetail, SessionMessage } from "./types";

const now = new Date();
const minutesAgo = (m: number) => new Date(now.getTime() - m * 60000).toISOString();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();

export const mockAgents: Agent[] = [
  {
    id: "agent-1",
    name: "code-reviewer",
    host: "prod-us-east-1",
    status: "running",
    lastHeartbeat: minutesAgo(0.5),
    costUsd: 4.82,
    tokenCount: 1_240_000,
    errorCount: 0,
  },
  {
    id: "agent-2",
    name: "deploy-bot",
    host: "prod-us-east-1",
    status: "running",
    lastHeartbeat: minutesAgo(1),
    costUsd: 2.15,
    tokenCount: 520_000,
    errorCount: 1,
  },
  {
    id: "agent-3",
    name: "data-pipeline",
    host: "prod-eu-west-1",
    status: "error",
    lastHeartbeat: minutesAgo(12),
    costUsd: 8.43,
    tokenCount: 2_100_000,
    errorCount: 7,
  },
  {
    id: "agent-4",
    name: "customer-support",
    host: "prod-us-west-2",
    status: "stuck",
    lastHeartbeat: minutesAgo(45),
    costUsd: 12.67,
    tokenCount: 3_400_000,
    errorCount: 3,
  },
  {
    id: "agent-5",
    name: "test-runner",
    host: "staging-1",
    status: "paused",
    lastHeartbeat: hoursAgo(2),
    costUsd: 1.03,
    tokenCount: 280_000,
    errorCount: 0,
  },
  {
    id: "agent-6",
    name: "doc-generator",
    host: "prod-us-east-1",
    status: "running",
    lastHeartbeat: minutesAgo(0.2),
    costUsd: 3.21,
    tokenCount: 890_000,
    errorCount: 0,
  },
  {
    id: "agent-7",
    name: "security-scanner",
    host: "prod-eu-west-1",
    status: "stopped",
    lastHeartbeat: hoursAgo(6),
    costUsd: 0.45,
    tokenCount: 120_000,
    errorCount: 0,
  },
  {
    id: "agent-8",
    name: "slack-responder",
    host: "prod-us-west-2",
    status: "running",
    lastHeartbeat: minutesAgo(0.1),
    costUsd: 6.89,
    tokenCount: 1_780_000,
    errorCount: 2,
  },
];

export const mockAlerts: Alert[] = [
  {
    id: "alert-1",
    agentId: "agent-4",
    type: "stuck",
    severity: "critical",
    message: "customer-support has not sent a heartbeat in 45 minutes",
    timestamp: minutesAgo(44),
    acknowledged: false,
  },
  {
    id: "alert-2",
    agentId: "agent-3",
    type: "error",
    severity: "critical",
    message: "data-pipeline encountered 7 errors in the last hour",
    timestamp: minutesAgo(10),
    acknowledged: false,
  },
  {
    id: "alert-3",
    agentId: "agent-4",
    type: "cost_spike",
    severity: "warning",
    message: "customer-support cost increased 340% in the last hour",
    timestamp: hoursAgo(1),
    acknowledged: false,
  },
  {
    id: "alert-4",
    agentId: "agent-8",
    type: "loop_detected",
    severity: "warning",
    message: "slack-responder may be in a retry loop (similar outputs detected)",
    timestamp: minutesAgo(30),
    acknowledged: true,
  },
  {
    id: "alert-5",
    agentId: "agent-2",
    type: "error",
    severity: "info",
    message: "deploy-bot encountered a transient API error (auto-recovered)",
    timestamp: hoursAgo(3),
    acknowledged: true,
  },
];

export const mockCosts: CostData = {
  totalUsd: 39.65,
  byAgent: mockAgents.map((a) => ({
    agentId: a.id,
    name: a.name,
    costUsd: a.costUsd,
  })),
  byModel: [
    { model: "claude-sonnet-4-20250514", costUsd: 22.1 },
    { model: "claude-haiku-4-20250506", costUsd: 11.35 },
    { model: "gpt-4o", costUsd: 6.2 },
  ],
};

export const mockSessions: Session[] = [
  {
    id: "session-1",
    agentId: "ofek",
    title: "Build ClaWatch dashboard with real-time alerts",
    status: "active",
    costUsd: 3.47,
    tokenCount: 892_000,
    messageCount: 47,
    model: "claude-sonnet-4-20250514",
    startedAt: minutesAgo(45),
    lastActivityAt: minutesAgo(1),
    duration: 2640,
  },
  {
    id: "session-2",
    agentId: "anas",
    title: "Fix authentication bug in user login flow",
    status: "completed",
    costUsd: 1.23,
    tokenCount: 340_000,
    messageCount: 22,
    model: "claude-sonnet-4-20250514",
    startedAt: hoursAgo(3),
    lastActivityAt: hoursAgo(2),
    duration: 3600,
  },
  {
    id: "session-3",
    agentId: "dor",
    title: "Review PR #47 — add retry logic to API calls",
    status: "idle",
    costUsd: 0.87,
    tokenCount: 215_000,
    messageCount: 14,
    model: "claude-haiku-4-20250506",
    startedAt: minutesAgo(90),
    lastActivityAt: minutesAgo(12),
    duration: 4680,
  },
  {
    id: "session-4",
    agentId: "ofek",
    title: "Implement WebSocket event streaming for agent heartbeats",
    status: "active",
    costUsd: 5.12,
    tokenCount: 1_340_000,
    messageCount: 63,
    model: "claude-sonnet-4-20250514",
    startedAt: hoursAgo(1.5),
    lastActivityAt: minutesAgo(0.5),
    duration: 5400,
  },
  {
    id: "session-5",
    agentId: "anas",
    title: "Refactor database schema for multi-tenant support",
    status: "completed",
    costUsd: 2.89,
    tokenCount: 780_000,
    messageCount: 38,
    model: "claude-sonnet-4-20250514",
    startedAt: hoursAgo(5),
    lastActivityAt: hoursAgo(4),
    duration: 3600,
  },
  {
    id: "session-6",
    agentId: "dor",
    title: "Debug failing CI pipeline — Jest timeout errors",
    status: "idle",
    costUsd: 0.54,
    tokenCount: 145_000,
    messageCount: 11,
    model: "claude-haiku-4-20250506",
    startedAt: minutesAgo(30),
    lastActivityAt: minutesAgo(8),
    duration: 1320,
  },
  {
    id: "session-7",
    agentId: "ofek",
    title: "Add Telegram bot notification integration",
    status: "completed",
    costUsd: 1.76,
    tokenCount: 460_000,
    messageCount: 29,
    model: "claude-sonnet-4-20250514",
    startedAt: hoursAgo(8),
    lastActivityAt: hoursAgo(7),
    duration: 3600,
  },
  {
    id: "session-8",
    agentId: "anas",
    title: "Write unit tests for cost calculation module",
    status: "active",
    costUsd: 0.92,
    tokenCount: 248_000,
    messageCount: 18,
    model: "claude-haiku-4-20250506",
    startedAt: minutesAgo(15),
    lastActivityAt: minutesAgo(2),
    duration: 780,
  },
  {
    id: "session-9",
    agentId: "dor",
    title: "Optimize SQL queries — reduce p95 latency from 800ms to 200ms",
    status: "completed",
    costUsd: 4.31,
    tokenCount: 1_120_000,
    messageCount: 52,
    model: "claude-sonnet-4-20250514",
    startedAt: hoursAgo(12),
    lastActivityAt: hoursAgo(10),
    duration: 7200,
  },
  {
    id: "session-10",
    agentId: "ofek",
    title: "Set up Docker Compose for local development environment",
    status: "idle",
    costUsd: 0.63,
    tokenCount: 172_000,
    messageCount: 9,
    model: "claude-haiku-4-20250506",
    startedAt: minutesAgo(60),
    lastActivityAt: minutesAgo(20),
    duration: 2400,
  },
];

function buildMockMessages(sessionId: string): SessionMessage[] {
  const base = [
    {
      id: `${sessionId}-msg-1`,
      role: "user" as const,
      timestamp: minutesAgo(44),
      content: "Build the ClaWatch dashboard with real-time alert monitoring. Use Next.js 15 with shadcn/ui components.",
    },
    {
      id: `${sessionId}-msg-2`,
      role: "assistant" as const,
      timestamp: minutesAgo(43),
      content: "I'll build the ClaWatch dashboard. Let me start by examining the project structure and existing code.",
      model: "claude-sonnet-4-20250514",
      costUsd: 0.03,
      tokenCount: 12_400,
    },
    {
      id: `${sessionId}-msg-3`,
      role: "tool" as const,
      timestamp: minutesAgo(43),
      content: "src/\n  app/\n    dashboard/\n      page.tsx\n    layout.tsx\n    page.tsx\n  components/\n    ui/\n  lib/\n    types.ts\n    api.ts\n    mock-data.ts",
      toolName: "read",
      toolInput: '{"path": "src/"}',
    },
    {
      id: `${sessionId}-msg-4`,
      role: "assistant" as const,
      timestamp: minutesAgo(42),
      content: "I can see the project structure. Let me read the existing types and API files to understand the data model.",
      model: "claude-sonnet-4-20250514",
      costUsd: 0.02,
      tokenCount: 8_200,
    },
    {
      id: `${sessionId}-msg-5`,
      role: "tool" as const,
      timestamp: minutesAgo(42),
      content: 'export type AgentStatus = "running" | "paused" | "stopped" | "error" | "stuck";\n\nexport interface Agent {\n  id: string;\n  name: string;\n  ...',
      toolName: "read",
      toolInput: '{"path": "src/lib/types.ts"}',
    },
    {
      id: `${sessionId}-msg-6`,
      role: "assistant" as const,
      timestamp: minutesAgo(40),
      content: "Now I'll create the dashboard page with agent cards, alert banners, and cost overview panels. I'll use the existing shadcn/ui components.",
      model: "claude-sonnet-4-20250514",
      costUsd: 0.08,
      tokenCount: 34_600,
    },
    {
      id: `${sessionId}-msg-7`,
      role: "tool" as const,
      timestamp: minutesAgo(39),
      content: "File written: src/app/dashboard/page.tsx (358 lines)",
      toolName: "write",
      toolInput: '{"path": "src/app/dashboard/page.tsx", "content": "..."}',
    },
    {
      id: `${sessionId}-msg-8`,
      role: "tool" as const,
      timestamp: minutesAgo(38),
      content: "$ npm run build\n\n ✓ Compiled successfully\n ✓ Collecting page data\n ✓ Generating static pages (5/5)\n ✓ Collecting build traces\n\nRoute (app)                 Size     First Load JS\n├ ○ /                       5.2 kB   92.1 kB\n└ ○ /dashboard              12.4 kB  99.3 kB",
      toolName: "exec",
      toolInput: '{"command": "npm run build"}',
    },
    {
      id: `${sessionId}-msg-9`,
      role: "assistant" as const,
      timestamp: minutesAgo(37),
      content: "The build succeeded. Let me now add the real-time polling mechanism and alert notification sounds.",
      model: "claude-sonnet-4-20250514",
      costUsd: 0.04,
      tokenCount: 15_800,
    },
    {
      id: `${sessionId}-msg-10`,
      role: "tool" as const,
      timestamp: minutesAgo(36),
      content: "Lines 49-64 edited in src/app/dashboard/page.tsx",
      toolName: "edit",
      toolInput: '{"path": "src/app/dashboard/page.tsx", "old_string": "...", "new_string": "..."}',
    },
    {
      id: `${sessionId}-msg-11`,
      role: "user" as const,
      timestamp: minutesAgo(35),
      content: "Can you also add a cost breakdown by model? Show it as horizontal progress bars.",
    },
    {
      id: `${sessionId}-msg-12`,
      role: "assistant" as const,
      timestamp: minutesAgo(34),
      content: "Sure! I'll add a cost breakdown section with progress bars for each model. Let me update the dashboard.",
      model: "claude-sonnet-4-20250514",
      costUsd: 0.06,
      tokenCount: 24_200,
    },
    {
      id: `${sessionId}-msg-13`,
      role: "tool" as const,
      timestamp: minutesAgo(33),
      content: "Lines 254-305 edited in src/app/dashboard/page.tsx",
      toolName: "edit",
      toolInput: '{"path": "src/app/dashboard/page.tsx", "old_string": "...", "new_string": "..."}',
    },
    {
      id: `${sessionId}-msg-14`,
      role: "system" as const,
      timestamp: minutesAgo(32),
      content: "Context window: 78% utilized (156K/200K tokens)",
    },
    {
      id: `${sessionId}-msg-15`,
      role: "assistant" as const,
      timestamp: minutesAgo(31),
      content: "I've added the cost breakdown panels. The dashboard now shows:\n\n1. **Agent cards** with status, cost, tokens, errors, and heartbeat\n2. **Alert banner** for critical/warning alerts\n3. **Cost by Agent** — horizontal progress bars\n4. **Cost by Model** — horizontal progress bars\n\nThe data refreshes every 5 seconds via polling.",
      model: "claude-sonnet-4-20250514",
      costUsd: 0.05,
      tokenCount: 18_900,
    },
    {
      id: `${sessionId}-msg-16`,
      role: "tool" as const,
      timestamp: minutesAgo(30),
      content: '{"results": [{"title": "shadcn/ui Tabs Component", "url": "https://ui.shadcn.com/docs/components/tabs"}]}',
      toolName: "web_search",
      toolInput: '{"query": "shadcn ui tabs component usage"}',
    },
    {
      id: `${sessionId}-msg-17`,
      role: "assistant" as const,
      timestamp: minutesAgo(28),
      content: "Let me add a tabbed interface for Agents and Sessions views. I'll implement the tabs using a simple state-based approach.",
      model: "claude-sonnet-4-20250514",
      costUsd: 0.11,
      tokenCount: 45_200,
    },
    {
      id: `${sessionId}-msg-18`,
      role: "tool" as const,
      timestamp: minutesAgo(27),
      content: "$ npm run build\n\n ✓ Compiled successfully\n ✓ Linting and checking validity of types\n ✓ Generating static pages (5/5)\n\nBuild completed in 8.2s",
      toolName: "exec",
      toolInput: '{"command": "npm run build"}',
    },
    {
      id: `${sessionId}-msg-19`,
      role: "assistant" as const,
      timestamp: minutesAgo(25),
      content: "Build passes. The dashboard now has Agents and Sessions tabs with full filtering and sorting. All existing functionality is preserved.",
      model: "claude-sonnet-4-20250514",
      costUsd: 0.03,
      tokenCount: 11_600,
    },
    {
      id: `${sessionId}-msg-20`,
      role: "tool" as const,
      timestamp: minutesAgo(24),
      content: "$ npm test -- --watchAll=false\n\nTest Suites: 3 passed, 3 total\nTests:       12 passed, 12 total\nTime:        4.231s",
      toolName: "exec",
      toolInput: '{"command": "npm test -- --watchAll=false"}',
    },
  ];
  return base;
}

export const mockSessionDetails: Record<string, SessionDetail> = {};

for (const session of mockSessions) {
  mockSessionDetails[session.id] = {
    ...session,
    costByModel: session.model.includes("sonnet")
      ? [
          { model: "claude-sonnet-4-20250514", costUsd: session.costUsd * 0.82, tokenCount: Math.floor(session.tokenCount * 0.75) },
          { model: "claude-haiku-4-20250506", costUsd: session.costUsd * 0.18, tokenCount: Math.floor(session.tokenCount * 0.25) },
        ]
      : [
          { model: "claude-haiku-4-20250506", costUsd: session.costUsd * 0.65, tokenCount: Math.floor(session.tokenCount * 0.6) },
          { model: "claude-sonnet-4-20250514", costUsd: session.costUsd * 0.35, tokenCount: Math.floor(session.tokenCount * 0.4) },
        ],
    tokenBreakdown: {
      input: Math.floor(session.tokenCount * 0.35),
      output: Math.floor(session.tokenCount * 0.30),
      cacheRead: Math.floor(session.tokenCount * 0.25),
      cacheWrite: Math.floor(session.tokenCount * 0.10),
    },
    messages: buildMockMessages(session.id),
  };
}
